export const authActionTypes = {
  SET_USER: "SET_USER",
  LOGOUT: "LOGOUT",
  SET_ERROR: "SET_ERROR",
  SET_LOADING: "SET_LOADING",
};

export const postActionTypes = {
  GET_POST: "GET_POST",
  SET_ERROR: "SET_ERROR",
  GET_POSTS_SUCCESS: "GET_POSTS_SUCCESS",
  GET_DRAFT_POSTS: "GET_DRAFT_POSTS",
  GET_DRAFT_POST: "GET_DRAFT_POST",
  SET_LOADING: "SET_LOADING",
  CREATE_POST: "CREATE_POST",
  UPDATE_POST: "UPDATE_POST",
  DELETE_POST: "DELETE_POST",
  DELETE_DRAFT_POST: "DELETE_DRAFT_POST",
  UPDATE_DRAFT_POST: "UPDATE_DRAFT_POST",
  PUBLISH_DRAFT_POST: "PUBLISH_DRAFT_POST",
};
export const categoryActionTypes = {
  GET_CATEGORY_SUCCESS: "GET_CATEGORY_SUCCESS",
  SET_LOADING: "SET_LOADING",
  CREATE_CATEGORY: "CREATE_CATEGORY",
  UPDATE_CATEGORY: "UPDATE_CATEGORY",
  DELETE_CATEGORY: "DELETE_CATEGORY",
};
