export const authActionTypes = {
  SET_USER: "SET_USER",
  LOGOUT: "LOGOUT",
  SET_ERROR: "SET_ERROR",
  SET_LOADING: "SET_LOADING",
};

export const postActionTypes = {
  SET_POSTS: "SET_POSTS",
  SET_POST: "SET_POST",
  SET_ERROR: "SET_ERROR",
  SET_LOADING: "SET_LOADING",
  CREATE_POST: "CREATE_POST",
  UPDATE_POST: "UPDATE_POST",
  DELETE_POST: "DELETE_POST",
  SET_DRAFTS: "SET_DRAFTS",
  UPDATE_DRAFT: "UPDATE_DRAFT",
};
3;
